jQuery(function ($) {
    var download_button = $('#configuration-download');

    // Create a blob object.
    var bb = new Blob(
        ["---\naudit:\n  parameter_values: true\n  mode: super\n  exclude_vector_patterns: []\n  include_vector_patterns: []\n  link_templates: []\n  links: true\n  forms: true\n  cookies: true\n  headers: true\n  jsons: true\n  xmls: true\n  ui_inputs: true\n  ui_forms: true\ndatastore: {}\ndevice:\n  visible: false\n  width: 1600\n  height: 1200\n  user_agent: Mozilla/5.0 (Gecko) SCNR::Engine/v1.0dev\n  pixel_ratio: 1.0\n  touch: false\ndom:\n  engine: chrome\n  local_storage: {}\n  session_storage: {}\n  wait_for_elements: {}\n  pool_size: 1\n  job_timeout: 120\n  worker_time_to_live: 1000\n  wait_for_timers: false\nhttp:\n  request_timeout: 20000\n  request_redirect_limit: 5\n  request_concurrency: 10\n  request_queue_size: 50\n  request_headers: {}\n  response_max_size: 500000\n  cookies: {}\n  authentication_type: auto\ninput:\n  values: {}\n  default_values:\n    name: scnr_engine_name\n    user: scnr_engine_user\n    usr: scnr_engine_user\n    pass: 5543!%scnr_engine_secret\n    txt: scnr_engine_text\n    num: '132'\n    amount: '100'\n    mail: scnr_engine@email.gr\n    account: '12'\n    id: '1'\n  without_defaults: false\n  force: false\nscope:\n  directory_depth_limit: 10\n  auto_redundant_paths: 15\n  redundant_path_patterns: {}\n  dom_depth_limit: 4\n  dom_event_limit: 500\n  dom_event_inheritance_limit: 500\n  exclude_file_extensions:\n  - gif\n  - bmp\n  - tif\n  - tiff\n  - jpg\n  - jpeg\n  - jpe\n  - pjpeg\n  - png\n  - ico\n  - psd\n  - xcf\n  - 3dm\n  - max\n  - svg\n  - eps\n  - drw\n  - ai\n  - asf\n  - rm\n  - mpg\n  - mpeg\n  - mpe\n  - 3gp\n  - 3g2\n  - avi\n  - flv\n  - mov\n  - mp4\n  - swf\n  - vob\n  - wmv\n  - aif\n  - mp3\n  - mpa\n  - ra\n  - wav\n  - wma\n  - mid\n  - m4a\n  - ogg\n  - flac\n  - zip\n  - zipx\n  - tar\n  - gz\n  - 7z\n  - rar\n  - bz2\n  - bin\n  - cue\n  - dmg\n  - iso\n  - mdf\n  - vcd\n  - raw\n  - exe\n  - apk\n  - app\n  - jar\n  - pkg\n  - deb\n  - rpm\n  - msi\n  - ttf\n  - otf\n  - woff\n  - woff2\n  - fon\n  - fnt\n  - css\n  - js\n  - pdf\n  - docx\n  - xlsx\n  - pptx\n  - odt\n  - odp\n  exclude_path_patterns: []\n  exclude_content_patterns: []\n  include_path_patterns: []\n  restrict_paths: []\n  extend_paths: []\n  url_rewrites: {}\nsession: {}\ntimeout: {}\nchecks:\n- \"*\"\n- \"-passive/*\"\nplatforms: []\nplugins:\n  proxy: {}\nno_fingerprinting: false\nauthorized_by: \nurl: http://localhost/\n"],
        { type : 'application/yaml' }
    );

    download_button.attr( 'href', window.URL.createObjectURL( bb ) );
    download_button.attr( 'download', 'localhost-profile.afp' );
});
